# Generated by Django 4.2.3 on 2023-07-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='active_update_timestamps',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
