# Generated by Django 4.2.3 on 2023-07-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rating_active_update_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-active_update_timestamps', '-active']},
        ),
    ]
