# Generated by Django 4.2.3 on 2023-07-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_rating_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-timestamps']},
        ),
    ]
